/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DawahRouteImport } from './routes/dawah'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as EventsRouteImport } from './routes/events'
import { Route as FamilySupportRouteImport } from './routes/family-support'
import { Route as FoodBankRouteImport } from './routes/food-bank'
import { Route as GetInvolvedRouteImport } from './routes/get-involved'
import { Route as HalaqasRouteImport } from './routes/halaqas'
import { Route as MadrasaRouteImport } from './routes/madrasa'
import { Route as MediaRouteImport } from './routes/media'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as TeamRouteImport } from './routes/team'
import { Route as YouthRouteImport } from './routes/youth'
import { Route as ZakatRouteImport } from './routes/zakat'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DawahRoute = DawahRouteImport.update({
  id: '/dawah',
  path: '/dawah',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilySupportRoute = FamilySupportRouteImport.update({
  id: '/family-support',
  path: '/family-support',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodBankRoute = FoodBankRouteImport.update({
  id: '/food-bank',
  path: '/food-bank',
  getParentRoute: () => rootRouteImport,
} as any)
const GetInvolvedRoute = GetInvolvedRouteImport.update({
  id: '/get-involved',
  path: '/get-involved',
  getParentRoute: () => rootRouteImport,
} as any)
const HalaqasRoute = HalaqasRouteImport.update({
  id: '/halaqas',
  path: '/halaqas',
  getParentRoute: () => rootRouteImport,
} as any)
const MadrasaRoute = MadrasaRouteImport.update({
  id: '/madrasa',
  path: '/madrasa',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaRoute = MediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const YouthRoute = YouthRouteImport.update({
  id: '/youth',
  path: '/youth',
  getParentRoute: () => rootRouteImport,
} as any)
const ZakatRoute = ZakatRouteImport.update({
  id: '/zakat',
  path: '/zakat',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dawah': typeof DawahRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/family-support': typeof FamilySupportRoute
  '/food-bank': typeof FoodBankRoute
  '/get-involved': typeof GetInvolvedRoute
  '/halaqas': typeof HalaqasRoute
  '/madrasa': typeof MadrasaRoute
  '/media': typeof MediaRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/team': typeof TeamRoute
  '/youth': typeof YouthRoute
  '/zakat': typeof ZakatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dawah': typeof DawahRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/family-support': typeof FamilySupportRoute
  '/food-bank': typeof FoodBankRoute
  '/get-involved': typeof GetInvolvedRoute
  '/halaqas': typeof HalaqasRoute
  '/madrasa': typeof MadrasaRoute
  '/media': typeof MediaRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/team': typeof TeamRoute
  '/youth': typeof YouthRoute
  '/zakat': typeof ZakatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/dawah': typeof DawahRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/family-support': typeof FamilySupportRoute
  '/food-bank': typeof FoodBankRoute
  '/get-involved': typeof GetInvolvedRoute
  '/halaqas': typeof HalaqasRoute
  '/madrasa': typeof MadrasaRoute
  '/media': typeof MediaRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/team': typeof TeamRoute
  '/youth': typeof YouthRoute
  '/zakat': typeof ZakatRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/dawah'
    | '/donate'
    | '/events'
    | '/family-support'
    | '/food-bank'
    | '/get-involved'
    | '/halaqas'
    | '/madrasa'
    | '/media'
    | '/policies'
    | '/privacy'
    | '/team'
    | '/youth'
    | '/zakat'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dawah'
    | '/donate'
    | '/events'
    | '/family-support'
    | '/food-bank'
    | '/get-involved'
    | '/halaqas'
    | '/madrasa'
    | '/media'
    | '/policies'
    | '/privacy'
    | '/team'
    | '/youth'
    | '/zakat'
    | '/blog/$slug'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/dawah'
    | '/donate'
    | '/events'
    | '/family-support'
    | '/food-bank'
    | '/get-involved'
    | '/halaqas'
    | '/madrasa'
    | '/media'
    | '/policies'
    | '/privacy'
    | '/team'
    | '/youth'
    | '/zakat'
    | '/blog/$slug'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  DawahRoute: typeof DawahRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  FamilySupportRoute: typeof FamilySupportRoute
  FoodBankRoute: typeof FoodBankRoute
  GetInvolvedRoute: typeof GetInvolvedRoute
  HalaqasRoute: typeof HalaqasRoute
  MadrasaRoute: typeof MadrasaRoute
  MediaRoute: typeof MediaRoute
  PoliciesRoute: typeof PoliciesRoute
  PrivacyRoute: typeof PrivacyRoute
  TeamRoute: typeof TeamRoute
  YouthRoute: typeof YouthRoute
  ZakatRoute: typeof ZakatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dawah': {
      id: '/dawah'
      path: '/dawah'
      fullPath: '/dawah'
      preLoaderRoute: typeof DawahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-support': {
      id: '/family-support'
      path: '/family-support'
      fullPath: '/family-support'
      preLoaderRoute: typeof FamilySupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food-bank': {
      id: '/food-bank'
      path: '/food-bank'
      fullPath: '/food-bank'
      preLoaderRoute: typeof FoodBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-involved': {
      id: '/get-involved'
      path: '/get-involved'
      fullPath: '/get-involved'
      preLoaderRoute: typeof GetInvolvedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/halaqas': {
      id: '/halaqas'
      path: '/halaqas'
      fullPath: '/halaqas'
      preLoaderRoute: typeof HalaqasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/madrasa': {
      id: '/madrasa'
      path: '/madrasa'
      fullPath: '/madrasa'
      preLoaderRoute: typeof MadrasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media': {
      id: '/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof MediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/youth': {
      id: '/youth'
      path: '/youth'
      fullPath: '/youth'
      preLoaderRoute: typeof YouthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zakat': {
      id: '/zakat'
      path: '/zakat'
      fullPath: '/zakat'
      preLoaderRoute: typeof ZakatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  DawahRoute: DawahRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  FamilySupportRoute: FamilySupportRoute,
  FoodBankRoute: FoodBankRoute,
  GetInvolvedRoute: GetInvolvedRoute,
  HalaqasRoute: HalaqasRoute,
  MadrasaRoute: MadrasaRoute,
  MediaRoute: MediaRoute,
  PoliciesRoute: PoliciesRoute,
  PrivacyRoute: PrivacyRoute,
  TeamRoute: TeamRoute,
  YouthRoute: YouthRoute,
  ZakatRoute: ZakatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
